steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/$fishpan-6d9ff/my-docker-repo/myimage', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/$fishpan-6d9ff/my-docker-repo/myimage']

  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances', 
           'create-with-container', 'my-vm-name',
           '--container-image', 
           'us-central1-docker.pkg.dev/$fishpan-6d9ff/my-docker-repo/myimage']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=australia-southeast1 (Sydney)'
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1 (Sydney)'